[tool.poetry]
name = "consumer"
version = "0.1.0"
description = ""
authors = ["Pedro LÃ³pez Mareque <pedro.lopez.mareque@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
expects = "^0.9.0"
pika = "^1.3.2"
pytest = "^8.3.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
